#define Napores2_VOLTAGE 0
#define Kpores2_VOLTAGE 0
#define GENsynpores_VOLTAGE 0
#define GENsynpores_TRANSMITTER 1
#define GENvgpores_VOLTAGE 0
#define GENtabchan_MALPHA 0
#define GENtabchan_MBETA 1
#define GENtabchan_HALPHA 2
#define GENtabchan_HBETA 3
#define GENtabchan_CA_BINDING_SCALING 4
#define GENtabchan_VOLTAGE 5
#define GENGprotein_VOLTAGE 0
#define GENGprotein_TRANSMITTER 1
#define GENgap_VOLTAGE1 0
#define GENgap_VOLTAGE2 1
#define logistic_INPUT 0
#define logistic_THRESH 1
#define logistic_GAIN 2
#define logistic_AMPLITUDE 3
#define GENVhalf_VOLTAGE 0
#define GENsynpores3D_VOLTAGE 0
#define GENsynpores3D_TRANSMITTER 1
