
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.4.0
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 2.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.01   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m?]

*set_global	         EREST_ACT	-0.06  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high


// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
*set_compt_param     ELEAK -0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 1.4111996  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m?]


*spherical 

soma none 0 0 0 15.9576 

*cylindrical 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
dend__Extra_1 none 0 36.36364 0 4 CaV13 0.85 Ca_conc_r 5.18213e-6 SK2 12.0 SK2h 0.0 sAHP 12.0 HPo_SK2 12.0

