
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.4.0
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 2.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.01   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m?]

*set_global	         EREST_ACT	-0.06  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high

// Channel densities in units S/m^2 or pS/µm^2 (take your pick!)
// Ca_concs densities in mol/coloumb/m^3 if negative or mol/coloumb if positive (readcell divides this value by compartment area)
// lengths in units µm


// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)Ca_conc_r 2.07285e-8
*set_compt_param     ELEAK -0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     RM 1.4111996  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m?]

*cylindrical 

*double_endpoint
soma__Extra_0 none 0 0 0 0 0.1256511 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10
*double_endpoint_off

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_1 soma__Extra_0 0 0.2513022 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_2 soma__Extra_1 0 0.3769533 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_3 soma__Extra_2 0 0.5026044 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_4 soma__Extra_3 0 0.6282555 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_5 soma__Extra_4 0 0.7539066 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_6 soma__Extra_5 0 0.8795577 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_7 soma__Extra_6 0 1.005209 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_8 soma__Extra_7 0 1.13086 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_9 soma__Extra_8 0 1.256511 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_10 soma__Extra_9 0 1.382162 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_11 soma__Extra_10 0 1.507813 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_12 soma__Extra_11 0 1.633464 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_13 soma__Extra_12 0 1.759115 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_14 soma__Extra_13 0 1.884767 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_15 soma__Extra_14 0 2.010418 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_16 soma__Extra_15 0 2.136069 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_17 soma__Extra_16 0 2.26172 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_18 soma__Extra_17 0 2.387371 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_19 soma__Extra_18 0 2.513022 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_20 soma__Extra_19 0 2.638673 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_21 soma__Extra_20 0 2.764324 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_22 soma__Extra_21 0 2.889976 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_23 soma__Extra_22 0 3.015626 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_24 soma__Extra_23 0 3.141278 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_25 soma__Extra_24 0 3.266929 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_26 soma__Extra_25 0 3.39258 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_27 soma__Extra_26 0 3.518231 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_28 soma__Extra_27 0 3.643882 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_29 soma__Extra_28 0 3.769533 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_30 soma__Extra_29 0 3.895184 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_31 soma__Extra_30 0 4.020835 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_32 soma__Extra_31 0 4.146486 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_33 soma__Extra_32 0 4.272138 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_34 soma__Extra_33 0 4.397789 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_35 soma__Extra_34 0 4.52344 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_36 soma__Extra_35 0 4.649091 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_37 soma__Extra_36 0 4.774742 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_38 soma__Extra_37 0 4.900393 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_39 soma__Extra_38 0 5.026044 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_40 soma__Extra_39 0 5.151695 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_41 soma__Extra_40 0 5.277346 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_42 soma__Extra_41 0 5.402997 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_43 soma__Extra_42 0 5.528649 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_44 soma__Extra_43 0 5.6543 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_45 soma__Extra_44 0 5.779951 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_46 soma__Extra_45 0 5.905602 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_47 soma__Extra_46 0 6.031253 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_48 soma__Extra_47 0 6.156904 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_49 soma__Extra_48 0 6.282555 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_50 soma__Extra_49 0 6.408206 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_51 soma__Extra_50 0 6.533858 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_52 soma__Extra_51 0 6.659509 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_53 soma__Extra_52 0 6.78516 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_54 soma__Extra_53 0 6.910811 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_55 soma__Extra_54 0 7.036462 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_56 soma__Extra_55 0 7.162113 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_57 soma__Extra_56 0 7.287764 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_58 soma__Extra_57 0 7.413415 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_59 soma__Extra_58 0 7.539066 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_60 soma__Extra_59 0 7.664718 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_61 soma__Extra_60 0 7.790369 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_62 soma__Extra_61 0 7.916019 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_63 soma__Extra_62 0 8.041671 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_64 soma__Extra_63 0 8.167322 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_65 soma__Extra_64 0 8.292973 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_66 soma__Extra_65 0 8.418624 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_67 soma__Extra_66 0 8.544275 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_68 soma__Extra_67 0 8.669926 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_69 soma__Extra_68 0 8.795577 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_70 soma__Extra_69 0 8.921228 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_71 soma__Extra_70 0 9.04688 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_72 soma__Extra_71 0 9.172531 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_73 soma__Extra_72 0 9.298182 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_74 soma__Extra_73 0 9.423833 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_75 soma__Extra_74 0 9.549484 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_76 soma__Extra_75 0 9.675136 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_77 soma__Extra_76 0 9.800786 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_78 soma__Extra_77 0 9.926437 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_79 soma__Extra_78 0 10.05209 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_80 soma__Extra_79 0 10.17774 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_81 soma__Extra_80 0 10.30339 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_82 soma__Extra_81 0 10.42904 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_83 soma__Extra_82 0 10.55469 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_84 soma__Extra_83 0 10.68034 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_85 soma__Extra_84 0 10.80599 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_86 soma__Extra_85 0 10.93165 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_87 soma__Extra_86 0 11.0573 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_88 soma__Extra_87 0 11.18295 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_89 soma__Extra_88 0 11.3086 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_90 soma__Extra_89 0 11.43425 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_91 soma__Extra_90 0 11.5599 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_92 soma__Extra_91 0 11.68555 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_93 soma__Extra_92 0 11.8112 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_94 soma__Extra_93 0 11.93686 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_95 soma__Extra_94 0 12.06251 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_96 soma__Extra_95 0 12.18816 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_97 soma__Extra_96 0 12.31381 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_98 soma__Extra_97 0 12.43946 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_99 soma__Extra_98 0 12.56511 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_100 soma__Extra_99 0 12.69076 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_101 soma__Extra_100 0 12.81641 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_102 soma__Extra_101 0 12.94206 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_103 soma__Extra_102 0 13.06772 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_104 soma__Extra_103 0 13.19337 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_105 soma__Extra_104 0 13.31902 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_106 soma__Extra_105 0 13.44467 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_107 soma__Extra_106 0 13.57032 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_108 soma__Extra_107 0 13.69597 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_109 soma__Extra_108 0 13.82162 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_110 soma__Extra_109 0 13.94727 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_111 soma__Extra_110 0 14.07292 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_112 soma__Extra_111 0 14.19858 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_113 soma__Extra_112 0 14.32423 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_114 soma__Extra_113 0 14.44988 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_115 soma__Extra_114 0 14.57553 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_116 soma__Extra_115 0 14.70118 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_117 soma__Extra_116 0 14.82683 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_118 soma__Extra_117 0 14.95248 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_119 soma__Extra_118 0 15.07813 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_120 soma__Extra_119 0 15.20378 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_121 soma__Extra_120 0 15.32944 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_122 soma__Extra_121 0 15.45509 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_123 soma__Extra_122 0 15.58074 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_124 soma__Extra_123 0 15.70639 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma__Extra_125 soma__Extra_124 0 15.83204 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10 

// Cell mechanism: KConductance (density: 3.6E-7 mS um^-2)
// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
soma soma__Extra_125 0 15.95769 0 15.95769 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10

