
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.4.0
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RA 2.0  // using: Units[GENESIS_SI_specAxialResistance, symbol: ohm m]

*set_global	         CM 0.01   // using: Units[GENESIS_SI_specificCapacitance, symbol: F m-2]

*set_global	         RM	0.3333333  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m?]

*set_global	         EREST_ACT	-0.06  // using: Units[GENESIS_SI_voltage, symbol: V]

*set_compt_param     ELEAK	-0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]

*compt /library/compartment

// NOTE: readcell usually assumes SI units (meters, seconds, ohms) above and lengths (below)
// in micrometers. If we use physiological units above, the lengths below will appear quite high

// Channel densities in units S/m^2 or pS/µm^2 (take your pick!)
// Ca_concs densities in mol/coloumb/m^3 if negative or mol/coloumb if positive (readcell divides this value by compartment area)
// lengths in units µm


// Cell mechanism: LeakConductance (density: 7.08617E-10 mS um^-2)
// *set_compt_param     ELEAK -0.0594  // using: Units[GENESIS_SI_voltage, symbol: V]
*set_compt_param     ELEAK -0.0600  // davedit
*set_compt_param     RM 1.4111996  // using: Units[GENESIS_SI_specificMembraneResistance, symbol: ohm m?]


*spherical 

soma none 0 0 0 15.9576 NaDiba 240 KADiba 10 KSDiba 0.0 K_DR 500 leakDiba 0.0 CaV13 3.2 Ca_conc_r 2.07285e-8 SK2 10

